### Index page
GET localhost:8080

### getGraph page without start & end time
GET localhost:8080/getGraph?owner=microsoft&project=typescript

### getGraph page with only start time
GET localhost:8080/getGraph?owner=microsoft&project=typescript&start=2024-05-21T15:16:07.257Z

### getGraph page with only end time
GET localhost:8080/getGraph?owner=microsoft&project=typescript&end=2024-05-21T15:16:07.257Z

### getGraph page with both start & end time
GET localhost:8080/getGraph?owner=microsoft&project=typescript&start=2024-05-21T15:16:07.257Z&
    end=2024-05-21T15:16:07.257Z