spring.application.name=codereviewvisualisation
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306
spring.datasource.username=[redacted]
spring.datasource.password=[redacted]
spring.jpa.show-sql=true