spring.application.name=codereviewvisualisation
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#gemini.api.key=[YOUR_ACTUAL_API_KEY_HERE]
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent

